#!/bin/bash
#
# priority: 450
#
# Configure the API. Must be done after SSL certificates are generated
# and before the API web server is brought up.
#
# Mark Huang <mlhuang@cs.princeton.edu>
# Copyright (C) 2006 The Trustees of Princeton University
#
# $Id: api,v 1.3 2006/04/25 21:18:19 mlhuang Exp $
#

# Source function library and configuration
. /etc/plc.d/functions
. /etc/planetlab/plc_config

# Be verbose
set -x

case "$1" in
    start)
	if [ "$PLC_API_ENABLED" != "1" ] ; then
	    exit 0
	fi

	MESSAGE=$"Configuring the API"
	dialog "$MESSAGE"

	api-config
	check

	result "$MESSAGE"
	;;
esac

exit $ERRORS
