#!/bin/bash
#
# priority: 450
#
# Configure the API. Must be done after SSL certificates are generated
# and before the API web server is brought up.
#
# Mark Huang <mlhuang@cs.princeton.edu>
# Copyright (C) 2006 The Trustees of Princeton University
#
# $Id: api,v 1.5 2006/07/10 21:08:06 mlhuang Exp $
#

# Source function library and configuration
. /etc/plc.d/functions
. /etc/planetlab/plc_config

# Be verbose
set -x

case "$1" in
    start)
	if [ "$PLC_API_ENABLED" != "1" ] ; then
	    exit 0
	fi

	MESSAGE=$"Configuring the API"
	dialog "$MESSAGE"

	# Generate old DB configuration file
	ln -sf plc_config /etc/planetlab/plc_db

	# Make sure that the API maintenance account is protected by a
	# password.
	if [ -z "$PLC_API_MAINTENANCE_PASSWORD" ] ; then
	    PLC_API_MAINTENANCE_PASSWORD=$(uuidgen)
	    plc-config --category=plc_api --variable=maintenance_password --value="$PLC_API_MAINTENANCE_PASSWORD" --save
	fi

	# Make sure that all PLC servers are allowed to access the API
	# through the maintenance account.
	PLC_API_MAINTENANCE_SOURCES=$(
	    for server in API BOOT WWW ; do
		hostname=PLC_${server}_HOST
		gethostbyname ${!hostname}
	    done | sort -u
	)
	plc-config --category=plc_api --variable=maintenance_sources --value="$PLC_API_MAINTENANCE_SOURCES" --save

	result "$MESSAGE"
	;;
esac

exit $ERRORS
