#!/bin/bash
#
# priority: 1100
#
# Rebuild the Boot Manager
#
# Mark Huang <mlhuang@cs.princeton.edu>
# Copyright (C) 2006 The Trustees of Princeton University
#
# $Id: bootmanager,v 1.2 2006/04/25 21:18:19 mlhuang Exp $
#

# Source function library and configuration
. /etc/plc.d/functions
. /etc/planetlab/plc_config

# Be verbose
set -x

case "$1" in
    start)
	if [ "$PLC_BOOT_ENABLED" != "1" -a \
	     "$PLC_WWW_ENABLED" != "1" ] ; then
	    return 0
	fi

	MESSAGE=$"Rebuilding Boot Manager"
	dialog "$MESSAGE"

	# Customize the Boot Manager
	pushd /var/www/html/boot
	/usr/share/bootmanager/build.sh
	check
	popd

	result "$MESSAGE"
	;;
esac

exit $ERRORS
