#!/bin/bash
#
# priority: 1000
#
# Rebuild the Boot CD
#
# Mark Huang <mlhuang@cs.princeton.edu>
# Copyright (C) 2006 The Trustees of Princeton University
#
# $Id: bootcd 129 2007-03-20 12:04:03Z thierry $
#

# Source function library and configuration
. /etc/plc.d/functions
. /etc/planetlab/plc_config

# Be verbose
set -x

case "$1" in
    start)
	if [ "$PLC_BOOT_ENABLED" != "1" -a \
	     "$PLC_WWW_ENABLED" != "1" ] ; then
	    exit 0
	fi

	MESSAGE=$"Rebuilding Boot CD"
	dialog "$MESSAGE"

	# Customize the Boot CD
	pushd /var/www/html/download
	/usr/share/bootcd/build.sh
	check
	popd

	result "$MESSAGE"
	;;
esac

exit $ERRORS
