#!/bin/bash
#
# priority: 900
#
# Configure cron jobs
#
# Mark Huang <mlhuang@cs.princeton.edu>
# Copyright (C) 2006 The Trustees of Princeton University
#
# $Id: crond,v 1.1 2006/04/06 21:51:59 mlhuang Exp $
#

# Source function library and configuration
. /etc/plc.d/functions
. /etc/planetlab/plc_config

case "$1" in
    start)
	MESSAGE=$"Starting crond"
	dialog "$MESSAGE"

	if [ "$PLC_MAIL_ENABLED" = "1" ] ; then
	    MAILTO=$PLC_MAIL_SUPPORT_ADDRESS
	else
	    MAILTO=
	fi
	cat >/etc/cron.d/plc.cron <<EOF
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=$MAILTO
HOME=/

# minute hour day-of-month month day-of-week user command
*/5 * * * * root gen-slices-xml-05.py
*/15 * * * * root gen-sites-xml.py
*/15 * * * * root gen-static-content.py
EOF

        # Run them once at startup
	gen-slices-xml-05.py
	check
	gen-sites-xml.py
	check
	gen-static-content.py
	check

	plc_daemon crond
	check

	result "$MESSAGE"	
	;;

    stop)
	MESSAGE=$"Stopping crond"
	dialog "$MESSAGE"

	killproc plc_crond
	check

	result "$MESSAGE"	
	;;
esac

exit $ERRORS
