#!/bin/bash
#
# priority: 850
#
# Start local DNS server to provide minimal DNS forward resolution for
# ourselves and our nodes.
#
# Mark Huang <mlhuang@cs.princeton.edu>
# Copyright (C) 2006 The Trustees of Princeton University
#
# $Id$
#

# Source function library and configuration
. /etc/plc.d/functions
. /etc/planetlab/plc_config

# Be verbose
set -x

case "$1" in
    start)
	[ $PLC_DNS_ENABLED -ne 1 ] && exit 0

	MESSAGE=$"Starting DNS server"
	dialog "$MESSAGE"

	dns-config
	check

	plc_daemon dnsmasq
	check

	result "$MESSAGE"
	;;

    stop)
	[ $PLC_DNS_ENABLED -ne 1 ] && exit 0
	MESSAGE=$"Stopping DNS server"
	dialog "$MESSAGE"

	killproc plc_dnsmasq
	check

	result "$MESSAGE"
	;;
esac

exit $ERRORS
