#!/bin/bash
#
# priority: 500
#
# Generate GPG keys
#
# Mark Huang <mlhuang@cs.princeton.edu>
# Copyright (C) 2006 The Trustees of Princeton University
#
# $Id: gpg,v 1.7 2006/06/23 20:29:22 mlhuang Exp $
#

# Source function library and configuration
. /etc/plc.d/functions
. /etc/planetlab/plc_config

# Be verbose
set -x

case "$1" in
    start)
	if [ ! -f $PLC_ROOT_GPG_KEY_PUB -o ! -f $PLC_ROOT_GPG_KEY ] ; then
	    # Generate new GPG keyring
	    MESSAGE=$"Generating GPG keys"
	    dialog "$MESSAGE"

	    mkdir -p $(dirname $PLC_ROOT_GPG_KEY_PUB)
	    mkdir -p $(dirname $PLC_ROOT_GPG_KEY)

	    # Temporarily replace /dev/random with /dev/urandom to
	    # avoid running out of entropy.
	    rm -f /dev/random
	    mknod /dev/random c 1 9
	    gpg --homedir=/root --no-tty --yes \
		--batch --gen-key <<EOF
Key-Type: DSA
Key-Length: 1024
Subkey-Type: ELG-E
Subkey-Length: 1024
Name-Real: $PLC_NAME Central
Name-Comment: http://$PLC_WWW_HOST/
Name-Email: $PLC_MAIL_SUPPORT_ADDRESS
Expire-Date: 0
%pubring $PLC_ROOT_GPG_KEY_PUB
%secring $PLC_ROOT_GPG_KEY
%commit
EOF
	    check
	    rm -f /dev/random
	    mknod /dev/random c 1 8
	    # Make GPG key readable by apache so that the API can sign peer requests
	    chown apache $PLC_ROOT_GPG_KEY
	    chmod 644 $PLC_ROOT_GPG_KEY_PUB
	    chmod 600 $PLC_ROOT_GPG_KEY
	else
	    # Update GPG UID
	    MESSAGE=$"Updating GPG keys"
	    dialog "$MESSAGE"

	    # Get the current GPG fingerprint and comment
	    OLDIFS=$IFS
	    IFS=:
	    while read -a fields ; do
		if [ "${fields[0]}" = "pub" ] ; then
		    fingerprint=${fields[4]}
		    break
		fi
	    done < <(
		gpg --homedir=/etc/planetlab --no-permission-warning --no-tty --yes \
		    --list-public-keys --with-colons
		check
	    )
	    IFS=$OLDIFS

	    # Add a new UID if appropriate. GPG will detect and merge duplicates.
	    gpg --homedir=/etc/planetlab --no-permission-warning --no-tty --yes \
		--command-fd 0 --status-fd 1 --edit-key $fingerprint <<EOF
adduid
$PLC_NAME Central
$PLC_MAIL_SUPPORT_ADDRESS
http://$PLC_WWW_HOST/
save
EOF
	    check
	fi

	# Install the key in the RPM database
	mkdir -p /etc/pki/rpm-gpg
	gpg --homedir=/etc/planetlab --no-permission-warning --no-tty --yes \
	    --export --armor >"/etc/pki/rpm-gpg/RPM-GPG-KEY-$PLC_NAME"
	check
	if rpm -q gpg-pubkey ; then
	    rpm --allmatches -e gpg-pubkey
	    check
	fi
	rpm --import /etc/pki/rpm-gpg/*
	check

	result "$MESSAGE"
	;;
esac

exit $ERRORS
