#!/bin/bash
#
# priority: 250
#
# Start local mail server.
#
# Mark Huang <mlhuang@cs.princeton.edu>
# Copyright (C) 2006 The Trustees of Princeton University
#
# $Id: mail,v 1.1 2006/04/24 15:49:32 mlhuang Exp $
#

# Source function library and configuration
. /etc/plc.d/functions
. /etc/planetlab/plc_config

case "$1" in
    start)
	if [ "$PLC_MAIL_ENABLED" != "1" ] ; then
	    exit 0
	fi

	MESSAGE=$"Starting mail server"
	dialog "$MESSAGE"

	service sendmail start
	check

	result "$MESSAGE"
	;;

    stop)
	MESSAGE=$"Stopping mail server"
	dialog "$MESSAGE"

	service sendmail stop
	check

	result "$MESSAGE"
	;;
esac

exit $ERRORS
