#!/bin/bash
#
# priority: 100
#
# Manage network related configuration files
#
# Mark Huang <mlhuang@cs.princeton.edu>
# Copyright (C) 2006 The Trustees of Princeton University
#
# $Id: network 129 2007-03-20 12:04:03Z thierry $
#

# Source function library and configuration
. /etc/plc.d/functions
. /etc/planetlab/plc_config

# Be verbose
set -x

case "$1" in
    start)
	MESSAGE=$"Generating network files"
	dialog "$MESSAGE"

	# Minimal /etc/hosts
	echo "127.0.0.1	localhost.localdomain localhost" >/etc/hosts
	(
	    for server in DB API BOOT WWW ; do
		hostname=PLC_${server}_HOST
		ip=PLC_${server}_IP
		if [ -n "${!ip}" ] ; then
		    echo "${!ip}	${!hostname}"
		else
		    ip=$(gethostbyname ${!hostname})
		    if [ -n "$ip" ] ; then
			echo "$ip	${!hostname}"
		    fi
		fi
	    done
	) >>/etc/hosts

	# Set up nameservers
	(
	    [ -n "$PLC_NET_DNS1" ] && echo "nameserver $PLC_NET_DNS1"
	    [ -n "$PLC_NET_DNS2" ] && echo "nameserver $PLC_NET_DNS2"
	) >/etc/resolv.conf

	result "$MESSAGE"
	;;
esac

exit $ERRORS
